apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: test-cluster
  name: test-user
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: test-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Describe
        resource:
          name: test-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: test-group
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: test-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: test-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Describe
        resource:
          name: test-topic
          patternType: literal
          type: topic
    type: simple
